// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMocksplitter creates a new instance of Mocksplitter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMocksplitter(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mocksplitter {
	mock := &Mocksplitter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Mocksplitter is an autogenerated mock type for the splitter type
type Mocksplitter struct {
	mock.Mock
}

type Mocksplitter_Expecter struct {
	mock *mock.Mock
}

func (_m *Mocksplitter) EXPECT() *Mocksplitter_Expecter {
	return &Mocksplitter_Expecter{mock: &_m.Mock}
}

// SplitText provides a mock function for the type Mocksplitter
func (_mock *Mocksplitter) SplitText(text string) ([]string, error) {
	ret := _mock.Called(text)

	if len(ret) == 0 {
		panic("no return value specified for SplitText")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]string, error)); ok {
		return returnFunc(text)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []string); ok {
		r0 = returnFunc(text)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(text)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Mocksplitter_SplitText_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SplitText'
type Mocksplitter_SplitText_Call struct {
	*mock.Call
}

// SplitText is a helper method to define mock.On call
//   - text string
func (_e *Mocksplitter_Expecter) SplitText(text interface{}) *Mocksplitter_SplitText_Call {
	return &Mocksplitter_SplitText_Call{Call: _e.mock.On("SplitText", text)}
}

func (_c *Mocksplitter_SplitText_Call) Run(run func(text string)) *Mocksplitter_SplitText_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Mocksplitter_SplitText_Call) Return(strings []string, err error) *Mocksplitter_SplitText_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *Mocksplitter_SplitText_Call) RunAndReturn(run func(text string) ([]string, error)) *Mocksplitter_SplitText_Call {
	_c.Call.Return(run)
	return _c
}
