// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/firebase/genkit/go/ai"
	mock "github.com/stretchr/testify/mock"
)

// NewMockdoc creates a new instance of Mockdoc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockdoc(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mockdoc {
	mock := &Mockdoc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Mockdoc is an autogenerated mock type for the doc type
type Mockdoc struct {
	mock.Mock
}

type Mockdoc_Expecter struct {
	mock *mock.Mock
}

func (_m *Mockdoc) EXPECT() *Mockdoc_Expecter {
	return &Mockdoc_Expecter{mock: &_m.Mock}
}

// DocumentsFromTextFile provides a mock function for the type Mockdoc
func (_mock *Mockdoc) DocumentsFromTextFile(path string) ([]*ai.Document, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for DocumentsFromTextFile")
	}

	var r0 []*ai.Document
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]*ai.Document, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []*ai.Document); ok {
		r0 = returnFunc(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*ai.Document)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Mockdoc_DocumentsFromTextFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DocumentsFromTextFile'
type Mockdoc_DocumentsFromTextFile_Call struct {
	*mock.Call
}

// DocumentsFromTextFile is a helper method to define mock.On call
//   - path string
func (_e *Mockdoc_Expecter) DocumentsFromTextFile(path interface{}) *Mockdoc_DocumentsFromTextFile_Call {
	return &Mockdoc_DocumentsFromTextFile_Call{Call: _e.mock.On("DocumentsFromTextFile", path)}
}

func (_c *Mockdoc_DocumentsFromTextFile_Call) Run(run func(path string)) *Mockdoc_DocumentsFromTextFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Mockdoc_DocumentsFromTextFile_Call) Return(documents []*ai.Document, err error) *Mockdoc_DocumentsFromTextFile_Call {
	_c.Call.Return(documents, err)
	return _c
}

func (_c *Mockdoc_DocumentsFromTextFile_Call) RunAndReturn(run func(path string) ([]*ai.Document, error)) *Mockdoc_DocumentsFromTextFile_Call {
	_c.Call.Return(run)
	return _c
}
